### ISSUE TITLE
The presented PEM data is of an unknown type.

### ISSUE THREAD

**Issue by manishrana2016** [Nucleware/powershell-jwt#1]
**Powershell version: 7.1.2**
I have downloaded a private key file for a google cloud service account in json format. Extracted private_key value from json file and saved in outfile exampleprivkey.pem. 

Then used following code:
```Powershell
    Function Get-ExpiryTimeStamp {
        param (
            [int]$ValidForSeconds = 30
        )
        $exp = [int](Get-Date -UFormat %s) + $ValidForSeconds # Grab Unix Epoch Timestamp and add desired expiration.
        $exp
    }
    
    $exp = Get-ExpiryTimeStamp -ValidForSeconds 30
    $payloadClaims = @{"scope"="https://www.googleapis.com/auth/prediction"; "aud"="https://oauth2.googleapis.com/token"; "iat"=$exp-60}
    
    $secretprivatekey=Get-Content "./exampleprivkey.pem" -AsByteStream
    $token=New-JWT -Algorithm 'RS256' -Issuer 'myserviceaccount@gcproject.iam.gserviceaccount.com' -SecretKey 
    $secretprivatekey -ExpiryTimestamp $exp -PayloadClaims $payloadClaims
```
Following error shown in: C:\Users\Username\Documents\PowerShell\Modules\powershell-jwt\0.0.5\Signature\RS.psm1:25

![image](https://user-images.githubusercontent.com/17695892/107976275-4d49bb80-6fdf-11eb-88fb-c301250d9271.png)

**Comment by Uplink03** [comment]
This is a very late reply, but hopefully it help.

Does your PEM file look like this?
```
-----BEGIN PRIVATE KEY-----
Lots of characters
On several lines
-----END PRIVATE KEY-----
```

If not, that's the problem.
